### ISSUE TITLE
Build failure on platforms where char is unsigned

### ISSUE THREAD

**Issue by manisandro** [MmgTools/mmg#83] opened 2020-10-12 08:34 UTC
I.e. on arm arches:

    In file included from /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/inoutcpp_3d.cpp:37:
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:150:93: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    150 | static const          char MMG5_idirinv[4][4] = {{-1,0,1,2},{0,-1,2,1},{0,1,-1,2},{0,2,1,-1}};
        |                                                                                             ^
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:150:93: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:150:93: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:150:93: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    154 | static const          char MMG5_iarfinv[4][6] = { {-1,-1,-1,2,1,0}, {-1,1,2,-1,-1,0},{2,-1,1,-1,0,-1},{1,2,-1,0,-1,-1}};
        |                                                                                                                       ^
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    /builddir/build/BUILD/mmg-5.5.0/src/mmg3d/mmg3d.h:154:119: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
    gmake[2]: *** [CMakeFiles/libmmg3d_so.dir/build.make:540: CMakeFiles/libmmg3d_so.dir/src/mmg3d/inoutcpp_3d.cpp.o] Error 1

Can be worked around by explicitly marking the char as signed, but I suppose a better idea is to use the `cstdint` types `int8_t` throughout instead of `char` (and `unit8_t` instead of `unsigned char`).

**Comment by Algiane** [comment] 2020-10-12 15:38
Hi @manisandro ,

Thank you for this bug report. For now I don't have any access to arm cores and I can't reproduce the bug by cross-compiling (I have used dockcross for that).
Do you have any idea on how I can reproduce this  (maybe using another cross-compilation system)? 

Thank you by advance for your help,

Algiane

**Comment by manisandro** [comment] 2020-10-12 15:44
You can use https://copr.fedorainfracloud.org/, it also allows building for aarch64.

**Comment by Algiane** [comment] 2020-10-15 06:54
Hi @manisandro ,

Thank you for your help. I think that the issue is fixed: can you please confirm that the last master commit works for you too?

If yes I will package a new hotfix release.

Thank  you by advance,
Algiane

**Comment by manisandro** [comment] 2020-10-15 17:36
Thanks, that builds on all Fedora arches [1].

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=53532359

**Comment by Algiane** [comment] 2020-10-19 07:18
Thank you for your feedback,

The release 5.5.1 is available so close the issue.

Regards,
A.

**Closed by Algiane** 2020-10-19 07:18 UTC
