### ISSUE TITLE
Where to find the libmmgtypesf.h file?

### ISSUE THREAD

**Issue by Foadsf** [MmgTools/mmg#66] opened 2020-04-05 11:21 UTC
I'm working on the [Elmer FEM project](https://github.com/ElmerCSC/elmerfem/tree/wip/mac) and sometime during the CMake configuration I get the error:

<pre>
-- Mesh adaptation 2D/3D looking for [Mmg] tools 
--   Library not found: >MMG_FOUND< 
--     Missing: >MMG_INCLUDE_DIR< , >MMG_LIBRARY<, to compile MMG3DSolver
</pre>

digging into the codebase I found that there is a `libmmgtypesf.h` file to be included. searching the internet I found that it is part of the `mmg2d` and the source can be downloaded from [here](http://www.rpmfind.info/linux/RPM/fedora/29/x86_64/m/mmg2d-devel-5.3.11-1.fc29.i686.html). In order to unpack the `.rpm` package I installed the `rpm2cpio` via HomeBrew:

    brew install rpm2cpio

and then 

    rpm2cpio mmg-5.3.11-1.fc29.src.rpm | cpio -i -d

and then 

    tar -xf mmg-5.3.11.tar.gz 

however, there is no `libmmgtypesf.h` file here as far as I can see. I would appreciate it if you could help me know where I can find this file and the package it belongs to. I suppose it is a deprecated version or something? even though I need to find the source code somehow.

**Comment by Foadsf** [comment] 2020-04-05 11:31
OK, [here](https://forum.mmgtools.org/t/unable-to-use-the-library-after-update-master-in-git/167/4) it says:

> This file is automatically genereated by Mmg and we have moved its location since the 5.3 release (it is now in the build/src/common directory).

that weird, but if that's the case should I ignore the absence of this file and solve the above problem in another way?

**Comment by Algiane** [comment] 2020-04-06 07:29
Hi Foadsf,

You are right, all the fortran header (*f.h files) are automatically generated using scripts.
To try to help you, I need to know if we are facing an issue due to the fact that this header is missing or if the issue is in the detection of this header:
  - With the `ls` command, can you check the presence of the `libmmgtypesf.h` file in `/usr/include/mmg/mmg2d/` or in `/usr/local/include/mmg/mmg2d/` ? (note that in the path, you can replace `2d`  by `s` or `3d`, the header file must be copied in all the directories).
  - Are you using the `FindMmg*.cmake` file provided by Mmg in your `Find_Package` command?

Thank you by advance,

Algiane

**Comment by Foadsf** [comment] 2020-04-06 08:15
Dear @Algiane ,

* I don't have the `libmmgtypesf.h` file anywhere on my computer.
* [Here](https://github.com/ElmerCSC/elmerfem/blob/wip/mac/cmake/Modules/FindMMG.cmake) is the `FindMMG.cmake` file coming with Elmer's source code. 

Thanks for your kind support.

**Comment by Algiane** [comment] 2020-04-06 09:18
Ok,

Can confirm:
  - that you are on MacOS (I assume that because you are using homebrew)?
  - that you are sudoer on your laptop?

If yes, I can help you to clone the Mmg repo and to build and install Mmg (I think that you need the whole Mmg installation and not only Mmg2d and I don't understand why the install is not good when you untar the package that you have downloaded).

**Comment by Foadsf** [comment] 2020-04-06 09:28
I can confirm both. 

It would be great to compile MMG, but it would be even better if we could :

* embed the library into the Elmer project using `.gitmodules`, as I have unsuccessfully tired [here](https://github.com/ElmerCSC/elmerfem/blob/wip/mac/.gitmodules)
* Or add MMG to Conan or Vcpkg package managers ([here](https://github.com/MmgTools/mmg/issues/67) and [here](https://github.com/MmgTools/mmg/issues/68)), or even HomeBrew

**Comment by Algiane** [comment] 2020-04-06 09:47
- To install Mmg, you can clone Mmg with the following command (which is equivalent to your submodule, except that the submodule is done inside your project):

```bash
git clone https://github.com/MmgTools/mmg.git
```

Then, normally you must be able to build and install Mmg using the basic CMakes commands:
```bash
cd mmg
mkdir build && cd build
cmake ..
make 
sudo make install
```

  - for the gitmodule, what you have done is ok, but it only get the Mmg sources. You also need to build and install Mmg. Maybe you can try to use the `execute_process` command to build Mmg at CMake's configure step (to execute the previous `cmake && make && make install ` commands).
  - otherwise, you can also try to use an external_project_add as alternative, but it requires another layer of CMake because it runs at build time.
  - Ok for the packages (I am not used to this). I have an old homebrew recipe, I update the release version and I add it.

**Comment by Algiane** [comment] 2020-04-06 09:58
Finally I can't add the homebrew recipe: it does not work anymore as lot of dependencies where linked to the homebrew-science project that has been deleted.

**Comment by Foadsf** [comment] 2020-04-06 10:20
@Algiane , 

* I have successfully compiled and installed MMG and now the `libmmgtypesf.h` file resides in below directories:

  * `/usr/local/include/mmg/mmgs/`
  * `/usr/local/include/mmg/mmg2d/`
  * `/usr/local/include/mmg/mmg3d/`

* regarding the `.gitmodules` method, there are already a lot of mentions to MMG inside the [Elmer's codebase](https://github.com/ElmerCSC/elmerfem/tree/wip/mac). there seem to be even some prices of the MMG source code there. I know it is a horrible idea to just copy the source code of a library into your code and as I have suggested [here](https://github.com/ElmerCSC/elmerfem/issues/202) I want to clean it up and make sure the dependencies are modularized as much as possible. It would be a great help if you could take a look at the [wip/mac branch](https://github.com/ElmerCSC/elmerfem/tree/wip/mac) and give me some feedback to improve the MMG parts. 
* I am new to the CMake, I will learn the `external_project_add`
* regarding the HomeBrew I think we can apply for a new formula, If I can just find the right repository to request a new package/formula ([Tweet](https://twitter.com/fsfarimani/status/1247103743457443840?s=20))

**Comment by Foadsf** [comment] 2020-04-06 10:35
another great package manager is [Hunter](https://github.com/cpp-pm/hunter).  Ideally, if we have an `mmg` package we should be able to add `hunter_add_package(mmg)` and it will take care of everything else automatically (AFIK!). I think we should open a new package request for MMG [here](https://github.com/hunter-packages/gate).

**Comment by Algiane** [comment] 2020-04-09 11:57
Hello @Foadsf ,

  1. great!

  2. The CMake seems to be ok but I am not an expert.

  3. ExternalProject_add allows to clone a project and build it inside your repo so there are drawbacks but if your dependencies are hard to manage, it can be a good solution.

  4. Packages are convenient but they need to be updated at each new release of the software, which takes a lot of time.
 Mmg has the chance to benefit from the Debian package make by @manisandro that you have found but for now I don't have time to look myself at making packages... 

I hope that you will succeed in building Elmer/Ice and improving its CMake...

Regards,

Algiane

**Comment by Algiane** [comment] 2020-06-25 01:12
Hi @Foadsf,

Can I close this issue or did you have still problems with Mmg compilation?

Regards,
Algiane

**Closed** 2020-06-25 07:23 UTC
